### ISSUE TITLE
len(car_data.index) ~= 10

### ISSUE THREAD

**Issue by mgruben** [cshaley/crawl-cl#1]
In previous editions of the notebook, `len(car_data.index)` was around `200`, however when I run the notebook on my box, I'm only getting about `10` for `len(car_data.index)`.

Is there something I'm doing wrong?

**Comment by cshaley** [comment]
No.  Just comment out the city_list = ['dallas'] line, and you should get more results.  Check the value of city_list before that for loop right after the city_list=['dallas'] line and make sure it has >1 cities.
