### ISSUE TITLE
More attributes

### ISSUE THREAD

**Issue by cshaley** [cshaley/crawl-cl#3]
Save the item description and any other attributes that could be relevant to the pandas dataframe as well.

**Comment by mgruben** [comment]
Description is prepended in the raw HTML by `<section id="postingbody">` and postpended by `</section>`

I'm not terribly familiar with `bs`, but maybe just save that block for future parsing?

**Comment by cshaley** [comment]
Yeah, beautifulsoup is pretty simple - it's just a matter of taking time to do it.
